apiVersion: v1
kind: Service
metadata:
    name: "wlppocaks-d07b"
    labels:
        app: "wlppocaks-d07b"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "wlppocaks-d07b"
