on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: wlppoccicd.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.AZURE_CREDENTIALS }}
      id: login

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wlp-poc-aks9254 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wlp-poc-aks9254`
        fi
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wlp-poc-aks9254
        container-registry-url: wlppoccicd.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: wlppocaksdockerauth

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: wlp-poc-aks9254
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }}
        imagepullsecrets: |
          wlppocaksdockerauth
