name: Test Code & Dockerize App

on:
  pull_request:
    branches: [develop, master]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit test
        run: coverage run -m unittest tests.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
         fail_ci_if_error: true
         token: ${{ secrets.CODECOV_TOKEN }}
         flags: unittests
