name: Test Code & Dockerize App

on: 
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: python tests.py      
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
         fail_ci_if_error: true        
         token: ${{ secrets.CODECOV_TOKEN }}
         flags: unittests
  build-docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: api-even
          image-tag: latest
