name: Python package

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: test env secrets access
        run: |
          echo ${{ secrets.SERVER_URL }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: python tests.py

  build-docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: api-even
          image-tag: latest

  test-action-dependency:
    needs: echo-lol
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok, very lol"
